plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = project.mod_version
group = project.maven_group
base { archivesName = project.archives_base_name }

loom {
    splitEnvironmentSourceSets()
    mods {
        "zoomhehe" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

repositories {
    maven {
        name = 'Xander Maven'
        url = 'https://maven.isxander.dev/releases'
    }
    maven {
        name = 'TerraformersMC'
        url = 'https://maven.terraformersmc.com/'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    // No mappings line - 26.X is unobfuscated
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    implementation "dev.isxander:yet-another-config-lib:3.9.5+26.3-fabric"
    implementation "com.terraformersmc:modmenu:21.0.0"
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 25
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
    withSourcesJar()
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") { expand "version": project.version }
}

jar {
    from("LICENSE") { rename { "${it}_${project.archives_base_name}" } }
}
